### ISSUE TITLE
Great example ... 

### ISSUE THREAD

**Issue by jamesladd** [diegozanon/serverless-notifications#2]
Hey there,

This is a simple example with some very clean code.

In you blog post you mention that if messages were between two users you would create a new
topic. 

Just wondering, could you do that at runtime and where abouts in your code would you do this?

**Comment by zanon-io** [comment]
Hello @jamesladd,

Topics are not "created". You simply select a name and start to use it. Sorry for using this word in the blog.

What I wanted to say is that, if you want to have a private chanel, you need to **define** a new name that will be used only by the two users. If this name is a GUID, only those two users will know the name and only them will be able to listen to the communication.

Obviously, if you want to have a secure channel, GUID will not be a good solution. In this case, you need to use the `assumeRole` command to restrict the users to just access pre-defined topic names (and not all topic names).

Btw, thanks for opening this issue. I will leave it open until I have the time to update the post to fix this misleading part.

**Comment by jamesladd** [comment]
Thank you for the quick response.

I played a little w the Aws IOT console and it appeared I can publish and subscribe to any topic name without first having to pre-define it - just what I need 

Your response also confirms this which is important because I have not yet put this in code.

- James

**Comment by jamesladd** [comment]
Hi,

For my needs I wanted to use Cognito for unauthenticated and authenticated access as you describe in your blog post (at the bottom). This needed a few more things so I'm posting them here to help others.

Of course this JS could (and should be cleaned up):

In iot/index.js I changed  $('#btn-keys').on('click', () => {} to ....

    let region = 'ap-southeast-2';
    let iotKeys = {};

    $('#btn-keys').on('click', () => {

        AWS.config.region = region;
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId: 'ap-southeast-2:80076a38-0000-4df7-a105-901db526aa52',
        });

        AWS.config.credentials.get(() => {
          // Use these credentials with IoT
          iotKeys.accessKey = AWS.config.credentials.accessKeyId;
          iotKeys.secretKey = AWS.config.credentials.secretAccessKey;
          iotKeys.sessionToken = AWS.config.credentials.sessionToken;
          iotKeys.iotEndpoint = 'a369hr22un09h8.iot.ap-southeast-2.amazonaws.com';
          iotKeys.region = region;

          addLog(`Endpoint: ${iotKeys.iotEndpoint},
                  Region: ${iotKeys.region},
                  AccessKey: ${iotKeys.accessKey},
                  SecretKey: ${iotKeys.secretKey},
                  SessionToken: ${iotKeys.sessionToken}`);
        });

        $('#btn-keys').prop('disabled', true);
        $('#btn-connect').prop('disabled', false);
    });

The above code works but there are configuration items missing which would trip up the unwary.

Firstly, you need to support an iotEndpoint which you can get by creating an IOT device in the AWS console and when looking at the details of your Thing selecting the "Interact" item which will show the iotEndpoint in the field: 'Update your Thing Shadow using this Rest API Endpoint'
Maybe this isn't the ideal way (I'll be making an IOT endpoint with serverless.yml) but it worked for me.

Secondly, if you want unauthenticated access you need the Cognito Identity Provider set to enable this.
Again, I'll be using serverless.yml to define this but you can do to the AWS console -> Cognito -> Federated Identities (option next to User Pools) -> your identity pool -> edit identity pool
Then under Unauthenticated Identities check 'Enable access to unauthenticated identities'.

Note you can also get the right IdentityPoolId on this page.

I put all this together and now the Web example you have given works fine with Cognito and Unauthenticated Identities.

Thanks again for the example. I hope these editions help.

- James.

**Comment by zanon-io** [comment]
Thanks @jamesladd for your feedback! I will try to edit the post soon to improve it using your comments.

**Comment by jamesladd** [comment]
Thank you again for taking the time to do this example - it allowed me to quickly learn and move forward w something I’m doing.

Learn a lot about Aws IOT and IOT Things and IOT Rules so if I can return the favour please let me know

**Comment by jamesladd** [comment]
One issue you might want to address is that many people use webpack to build their projects and even though you don't here they might be following along with their own projects.
I'm using Webpack since it is the default for react-boilerplate. I could not include the AWS-SDK as you have done. I had to use the approach outlined here: https://www.andrewhfarmer.com/aws-sdk-with-webpack/
There is support from AWS for webpack now but unfortunately the way react-boilerplate does webpack means I can't really get this to work but the alternative approach (link) does.

On a side note, PLEASE could you show how to use the aws-iot-sdk with webpack ?

**Comment by zanon-io** [comment]
Hi @jamesladd, I'm using Webpack with the AWS SDK and the AWS IoT Device SDK, but just with the default configuration that comes with the [Create React App](https://github.com/facebookincubator/create-react-app).

**Comment by jamesladd** [comment]
I'm going that way too given my troubles with react-boilerplate.

**Comment by diegozanon** [comment]
Closing because the blog is dead now. Sorry.
