### ISSUE TITLE
Connection failed in your example

### ISSUE THREAD

**Issue by lecong** [diegozanon/serverless-notifications#4]
I test on your example but dose not work. Please help me check it.
![Screen Shot 2019-07-26 at 12 05 17 PM](https://user-images.githubusercontent.com/5519891/61927134-d03e9780-af9d-11e9-9666-ada84a0eaf2b.png)

**Comment by tconroy** [comment]
Also seeing this. I'm guessing the key has expired?

**Comment by diegozanon** [comment]
Fixed. Thank you. It was a problem with Symantec certificate authority, which made the old endpoints invalid for security issues.
